name: animalxref
description: An Animal Crossing New Horizons fish reference web application built with Flutter Web.

version: 1.7.0+1

environment:
  sdk: ">=2.7.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^1.0.0+5
  intl: ^0.16.1
  provider: ^4.1.1
  shared_preferences: ^0.5.7+1

flutter:
  uses-material-design: true

  assets:
    - assets/bugs.json
    - assets/fish.json
